name: flutex_admin
description: "Sunrise Admin Mobile App for Android & IOS"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  get: ^4.6.6
  http: ^1.2.2
  shared_preferences: ^2.3.3
  intl: ^0.18.1
  dio: ^5.7.0
  image_picker: ^1.1.2
  flutter_spinkit: ^5.2.1
  path_provider: ^2.1.5
  image_gallery_saver_plus: ^4.0.1
  flutter_svg: ^2.0.16
  cached_network_image: ^3.4.1
  lottie: ^3.1.3
  connectivity_plus: ^6.1.0
  introduction_screen: ^3.1.14
  date_field: ^6.0.3+1
  flutter_html: ^3.0.0-beta.2
  multi_dropdown: ^3.0.1
  contained_tab_bar_view: ^0.8.0
  carousel_slider: ^5.0.0
  flutter_widget_from_html: ^0.15.3
  syncfusion_flutter_charts: ^27.2.5
  html: ^0.15.4
  async: ^2.11.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animation/
    - assets/lang/

  fonts:
    - family: Montserrat-Arabic
      fonts:
        - asset: assets/fonts/Montserrat-Arabic-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Arabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Arabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Arabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Arabic-Bold.ttf
          weight: 700
